name: clean_on_dispatch

on: workflow_dispatch

concurrency:
  group: ci-preview-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  clean_backend:
    uses: jalantechnologies/platform-github/.github/workflows/clean.yml@v2.6
    with:
      app_name: boilerplate-website-backend
      app_env: preview
      branch: ${{ github.event.ref }}
    secrets:
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}

  clean_frontend:
    uses: jalantechnologies/platform-github/.github/workflows/clean.yml@v2.6
    with:
      app_name: boilerplate-website-frontend
      app_env: preview
      branch: ${{ github.event.ref }}
    secrets:
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
