name: preview_on_dispatch

on: workflow_dispatch

concurrency:
  group: ci-preview-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  preview_backend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.7
    with:
      app_name: boilerplate-website-backend
      app_env: preview
      app_hostname: '{1}-backend.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      build_context: 'api'
      build_args: |
        CI=true
        NODE_ENV=production
      deploy_root: 'lib/kube/backend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-website-backend
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}

  preview_frontend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.7
    needs: 'preview_backend'
    with:
      app_name: boilerplate-website-frontend
      app_env: preview
      app_hostname: '{1}-website.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      build_args: |
        CI=true
        NODE_ENV=production
        STRAPI_API_URL=${{ needs.preview_backend.outputs.deploy_url }}
        STRAPI_TOKEN=${{ vars.STRAPI_PREVIEW_TOKEN }}
      deploy_root: 'lib/kube/frontend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-website-frontend
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
