name: production_on_push

on:
  push:
    branches:
      - main

concurrency:
  group: ci-production-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  production_backend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.5
    with:
      app_name: boilerplate-website-backend
      app_env: production
      app_hostname: 'boilerplate-website-backend.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      build_args: |
        CI=true
        NODE_ENV=production
      build_context: 'api'
      deploy_root: 'lib/kube/backend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-website
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PRODUCTION_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}

  production_frontend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.5
    needs: 'production_backend'
    with:
      app_name: boilerplate-website-frontend
      app_env: production
      app_hostname: 'boilerplate-website.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      build_args: |
        CI=true
        NODE_ENV=production
        STRAPI_API_URL=${{ needs.production_backend.outputs.deploy_url }}
        STRAPI_TOKEN=9222c94edf92bef7ce25ad13fdae51c0255849788468ef67524f934f911bd4e45c03c89d9ba98c4a8c74d51dbcfc08adc20e2883e6c60c5de4a3eeb3ef46361fcd88a5723235e6ff74a5d6f569ff57716bd2198707bf2876a8d65525164cfc2ecfb1bb986eac62e271c3a345e2018b4261568258508816360eb8487c3d71f63b
      deploy_root: 'lib/kube/frontend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-website
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
